const map = new Map()
map.set("firstName", "Luke")
map.set("lastName", "Skywalker")
map.set("occupation", "Jedi Knight")
console.log(map.entries())
console.log(map.size)
console.log(map.has("firstName"))
console.log(map)
