const map = new Map()
const map = new Map()
map.set("name", "Azam")
map.set("lastName", "Sufiev")
map.set("age", "25")
map.set("country", "poland")
map.set("town", "Warszawa")
console.log(map.get("name"))
console.log(map.size)
console.log(map.keys())
console.log(map.has("name"))
// console.log(map.values())
// console.log(map.entries())
map.forEach((value, key, map) => console.log(value))
map.clear()
console.log(map)
