const mySet = new Set()
mySet.add(1)
mySet.add(5)
mySet.add(5)
mySet.add("some text")
const o = { a: 1, b: 2 }
mySet.add(o)
mySet.add({ a: 1, b: 2 })
console.log(mySet.keys())
console.log(mySet.size)
console.log(mySet.has(5))
mySet.delete(5)
console.log(mySet.has(5))
console.log(mySet.size)
console.log(mySet)
